pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/HOST_NAME.crt
  key: /etc/nebula/HOST_NAME.key

static_host_map:
  "10.69.69.1": ["LIGHTHOUSE_IP_ADDRESS:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.69.69.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: redirectors

    - port: any
      proto: any
      group: operator


  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: redirectors

    - port: any
      proto: any
      group: operator
