pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/HOST_NAME.crt
  key: /etc/nebula/HOST_NAME.key

static_host_map:

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
