pki:
  ca: /opt/infrastructure_setups/redteam-infrastructure/src/templates/certificates/ca.crt
  cert: /opt/infrastructure_setups/redteam-infrastructure/src/templates/certificates/operator.crt
  key: /opt/infrastructure_setups/redteam-infrastructure/src/templates/certificates/operator.key

static_host_map:
  "10.69.69.1": ["52.56.92.145:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.69.69.1"

listen:
  host: 0.0.0.0
  port: 4242

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: critical

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: any
      proto: any
      group: critical
